nao_dcm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Controllers ------------------------------------------------
  Head_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - HeadYaw
      - HeadPitch
  LeftArm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
  RightArm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
  Pelvis_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - LHipYawPitch
  LeftLeg_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - LHipRoll
      - LHipPitch
      - LKneePitch
  RightLeg_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - RHipRoll
      - RHipPitch
      - RKneePitch
  LeftFoot_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - LAnklePitch
      - LAnkleRoll
  RightFoot_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - RAnklePitch
      - RAnkleRoll
  Head_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - HeadYaw
      - HeadPitch
